[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mlkit"
version = "2023.05a0"
description = "MLKit: A quick way to start with machine and deep learning"
requires-python = ">=3.10"
license = {file = "LICENSE"}
keywords = ["deep learning", "training pipeline"]
authors = [
    {name = "Marco Mancini"},
    {name = "Mirko Stojiljkovic"},
    {name = "Jakub Walczak", email = "jakub.walczak@p.lodz.pl"},
    {name = "Shahbaz Alvi"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
dependencies = [
    "torch",
    "numpy>=1.23.0",
    "pydantic>=1.10.0",
    "scikit-learn>=1.2.0",
    "colormath",
    "tqdm",
    "typer-cli>=0.9.*",
    "toml; python_version=='3.10'"
]
dynamic = ["readme"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.dynamic]
readme = {file = "README.MD"}


[tool.pydocstyle]


[tool.mypy]
files = [
    "mlkit",
]

[project.scripts]
mlkit = "mlkit.cli.app:run"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]