conf: !!python/object:mlkit.nn.confmodels.Conf
  __dict__:
    base: !!python/object:mlkit.nn.confmodels.BaseConf
      __dict__:
        cuda_id: null
        experiment_name: handwritten_digit_classification
        log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        log_level: INFO
        seed: 0
      __fields_set__: !!set
        experiment_name: null
        log_format: null
        log_level: null
        seed: null
      __private_attribute_values__: {}
    dataset: !!python/object:mlkit.nn.confmodels.DatasetConf
      __dict__:
        predict: null
        target: D:\Projekty\CMCC\ml-kit\examples\train_cnn_mnist\./dataset.py::MNISTCustomDataset
        test: null
        train: !!python/object:mlkit.nn.confmodels.SplitDatasetConf
          __dict__:
            arguments: {}
            loader:
              batch_size: 150
              num_workers: 4
              shuffle: true
          __fields_set__: !!set
            arguments: null
            loader: null
          __private_attribute_values__: {}
        trainval: !!python/object:mlkit.nn.confmodels.SplitDatasetConf
          __dict__:
            arguments:
              root_dir: ./mnist
            loader: {}
          __fields_set__: !!set
            arguments: null
          __private_attribute_values__: {}
        validation: !!python/object:mlkit.nn.confmodels.SplitDatasetConf
          __dict__:
            arguments: {}
            loader:
              batch_size: 150
              num_workers: 4
              shuffle: false
          __fields_set__: !!set
            arguments: null
            loader: null
          __private_attribute_values__: {}
      __fields_set__: !!set
        target: null
        train: null
        trainval: null
        validation: null
      __private_attribute_values__: {}
    metrics:
      FBetaScore:
        beta: 0.1
        num_classes: 10
        task: multiclass
      Precision:
        num_classes: 10
        task: multiclass
    model: !!python/object:mlkit.nn.confmodels.ModelConf
      __dict__:
        arguments:
          dropout: 0.5
          input_dims: 1
          layers: 4
          output_dims: 10
        target: D:\Projekty\CMCC\ml-kit\examples\train_cnn_mnist\./model.py::SimpleCNN
      __fields_set__: !!set
        arguments: null
        target: null
      __private_attribute_values__: {}
    training: !!python/object:mlkit.nn.confmodels.TrainingConf
      __dict__:
        checkpoint: !!python/object:mlkit.nn.confmodels.CheckpointConf
          __dict__:
            every_n_train_steps: null
            filename: '{epoch}_{val_precision:.2f}_cnn'
            mode: max
            monitor:
              metric: Precision
              stage: val
            path: chckpt
            save_on_train_epoch_end: null
            save_top_k: 1
            save_weights_only: true
          __fields_set__: !!set
            filename: null
            mode: null
            monitor: null
            path: null
            save_top_k: null
          __private_attribute_values__: {}
        criterion: !!python/object:mlkit.nn.confmodels.CriterionConf
          __dict__:
            target: torch.nn::CrossEntropyLoss
            weight:
            - 0.1
            - 0.1
            - 0.1
            - 0.1
            - 0.1
            - 0.1
            - 0.1
            - 0.1
            - 0.1
            - 0.1
          __fields_set__: !!set
            target: null
            weight: null
          __private_attribute_values__: {}
        epoch_schedulers:
        - T_max: 100
          target: torch.optim.lr_scheduler::CosineAnnealingLR
        epochs: 10
        optimizer: !!python/object:mlkit.nn.confmodels.OptimizerConf
          __dict__:
            arguments:
              weight_decay: 0.01
            lr: 0.001
            target: torch.optim::Adam
          __fields_set__: !!set
            arguments: null
            lr: null
            target: null
          __private_attribute_values__: {}
      __fields_set__: !!set
        checkpoint: null
        criterion: null
        epoch_schedulers: null
        epochs: null
        optimizer: null
      __private_attribute_values__: {}
    validation: !!python/object:mlkit.nn.confmodels.ValidationConf
      __dict__:
        run_every_epoch: 1
      __fields_set__: !!set
        run_every_epoch: null
      __private_attribute_values__: {}
  __fields_set__: !!set
    base: null
    dataset: null
    metrics: null
    model: null
    training: null
    validation: null
  __private_attribute_values__: {}
