name: Publish MLKit package to TestPyPI

on: 
  release:
    types: [prereleased]  
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build MLKit and publish to TestPyPI
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build tool
        run: python3 -m pip install build --user
      - name: Build wheels
        run: python -m build --sdist --wheel --outdir=dist/ .
      - name: Publish MLKit to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          